# Generated by Django 2.2 on 2022-04-01 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='Name',
            new_name='name',
        ),
    ]
